### ISSUE TITLE
Extension no longer functions

### ISSUE THREAD

**Issue by LuxArgentum** [yudai-tiny-developer/live-catch-up#45]
I'm not sure when, but it seems that the extension no longer functions. I recently noticed that the current speed and latency no longer displays. I tried restarting, uninstall/reinstall, but I think that YouTube updated something that broke the extension. Is this just my side that is broken?

**Comment by yudai-tiny-developer** [comment]
#46 solved it
Currently preparing for release

**Comment by LuxArgentum** [comment]
Awesome! It's working again. Thanks!
